// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csdrraabfbrzteezkqkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZHJyYWFiZmJyenRlZXprcWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTcyMjgsImV4cCI6MjA2NTE3MzIyOH0.WB0aLwy_kjoo44tP7MLccqjJCWfcxes-j0ikjXOq8aU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);