// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grwgphzgyjwnusfsyabq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdyd2dwaHpneWp3bnVzZnN5YWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5OTExMjUsImV4cCI6MjA1MjU2NzEyNX0.g6aiQO5uGh6NybzZ_NIm338zrq5lfHuLhWeDnBDNdR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);